version: '3.8'

services:
  app:
    build: .
    container_name: schedule-app
    ports:
      - "3000:3000"
    volumes:
      # Volumen para persistir la base de datos
      - schedule-data:/app/server
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  schedule-data:
    driver: local
