"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { requireUserId } from "@/lib/auth-helpers";
import { db } from "@/lib/db";
import { fromZodError, type ActionState } from "@/lib/action-state";
import { generateBudgetSuggestion } from "./service";

const saveBudgetSchema = z.object({
  income: z.coerce.number<number>().min(0, "El ingreso no puede ser negativo."),
  recurringExpenses: z.coerce.number<number>().min(0, "No puede ser negativo."),
  variableExpenses: z.coerce.number<number>().min(0, "No puede ser negativo."),
  savings: z.coerce.number<number>().min(0, "No puede ser negativo."),
});

/** Guarda el presupuesto del mes editado manualmente por el usuario. */
export async function saveBudgetAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const userId = await requireUserId();
  const parsed = saveBudgetSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return fromZodError(parsed.error);

  const now = new Date();
  await db.budget.upsert({
    where: {
      userId_year_month: {
        userId,
        year: now.getFullYear(),
        month: now.getMonth() + 1,
      },
    },
    create: {
      userId,
      year: now.getFullYear(),
      month: now.getMonth() + 1,
      ...parsed.data,
      isAutoGenerated: false,
    },
    update: { ...parsed.data, isAutoGenerated: false },
  });

  revalidatePath("/presupuesto");
  return { ok: true, message: "Presupuesto guardado." };
}

/** Recalcula la propuesta automática y la guarda como presupuesto del mes. */
export async function regenerateBudgetAction() {
  const userId = await requireUserId();
  const suggestion = await generateBudgetSuggestion(userId);

  const now = new Date();
  await db.budget.upsert({
    where: {
      userId_year_month: {
        userId,
        year: now.getFullYear(),
        month: now.getMonth() + 1,
      },
    },
    create: {
      userId,
      year: now.getFullYear(),
      month: now.getMonth() + 1,
      income: suggestion.income,
      recurringExpenses: suggestion.recurringExpenses,
      variableExpenses: suggestion.variableExpenses,
      savings: suggestion.savings,
      isAutoGenerated: true,
    },
    update: {
      income: suggestion.income,
      recurringExpenses: suggestion.recurringExpenses,
      variableExpenses: suggestion.variableExpenses,
      savings: suggestion.savings,
      isAutoGenerated: true,
    },
  });

  revalidatePath("/presupuesto");
  return { ok: true, message: "Presupuesto recalculado con tus datos recientes." };
}
