import { db } from "@/lib/db";
import { getMonthlyAverages } from "@/modules/transactions/service";
import { getMonthlyRecurringTotal } from "@/modules/recurring-payments/service";

export interface BudgetDTO {
  income: number;
  recurringExpenses: number;
  variableExpenses: number;
  savings: number;
  /** income - recurring - variable - savings */
  available: number;
  isAutoGenerated: boolean;
  /** true si ya está guardado en la base de datos */
  persisted: boolean;
  year: number;
  month: number;
}

function withAvailable(
  budget: Omit<BudgetDTO, "available">,
): BudgetDTO {
  return {
    ...budget,
    available:
      budget.income -
      budget.recurringExpenses -
      budget.variableExpenses -
      budget.savings,
  };
}

/**
 * Genera una propuesta de presupuesto mensual a partir de:
 *  - ingresos promedio de los últimos 3 meses,
 *  - gastos históricos (para estimar el gasto variable),
 *  - pagos recurrentes activos,
 *  - metas de ahorro en curso (cuánto habría que apartar por mes).
 */
export async function generateBudgetSuggestion(userId: string) {
  const now = new Date();
  const [averages, recurringMonthly, goals] = await Promise.all([
    getMonthlyAverages(userId, 3),
    getMonthlyRecurringTotal(userId),
    db.savingsGoal.findMany({
      where: { userId, status: "ACTIVE" },
      select: { targetAmount: true, savedAmount: true, targetDate: true },
    }),
  ]);

  const income = Math.round(averages.avgIncome);
  const recurring = Math.round(recurringMonthly);
  // El gasto variable estimado es el gasto histórico menos lo que ya se
  // explica por pagos recurrentes.
  const variable = Math.round(Math.max(0, averages.avgExpense - recurring));

  // Necesidad mensual de las metas activas
  let goalNeeds = 0;
  for (const g of goals) {
    const remaining = Number(g.targetAmount) - Number(g.savedAmount);
    if (remaining <= 0) continue;
    const months = g.targetDate
      ? Math.max(
          1,
          (g.targetDate.getUTCFullYear() - now.getUTCFullYear()) * 12 +
            (g.targetDate.getUTCMonth() - now.getUTCMonth()),
        )
      : 12;
    goalNeeds += remaining / months;
  }

  const availableBeforeSavings = Math.max(0, income - recurring - variable);
  // Ahorro sugerido: lo que piden las metas, con un mínimo del 10% del
  // ingreso, sin exceder lo realmente disponible.
  const savings = Math.round(
    Math.min(
      availableBeforeSavings,
      Math.max(goalNeeds, income * 0.1),
    ),
  );

  return withAvailable({
    income,
    recurringExpenses: recurring,
    variableExpenses: variable,
    savings,
    isAutoGenerated: true,
    persisted: false,
    year: now.getFullYear(),
    month: now.getMonth() + 1,
  });
}

/**
 * Presupuesto del mes actual: el guardado por el usuario o, si no existe,
 * la propuesta generada automáticamente (sin persistir).
 */
export async function getCurrentBudget(userId: string): Promise<BudgetDTO> {
  const now = new Date();
  const saved = await db.budget.findUnique({
    where: {
      userId_year_month: {
        userId,
        year: now.getFullYear(),
        month: now.getMonth() + 1,
      },
    },
  });

  if (saved) {
    return withAvailable({
      income: Number(saved.income),
      recurringExpenses: Number(saved.recurringExpenses),
      variableExpenses: Number(saved.variableExpenses),
      savings: Number(saved.savings),
      isAutoGenerated: saved.isAutoGenerated,
      persisted: true,
      year: saved.year,
      month: saved.month,
    });
  }

  return generateBudgetSuggestion(userId);
}
