"use client";

import { useState, useTransition } from "react";
import { Loader2, Pencil, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";

import { saveBudgetAction, regenerateBudgetAction } from "@/modules/budgets/actions";
import type { BudgetDTO } from "@/modules/budgets/service";
import { useDialogAction } from "@/lib/use-dialog-action";
import { cn, formatMoney } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import {
  FieldError,
  FormMessage,
  FormRow,
  SubmitButton,
} from "@/components/shared/form-bits";

const SEGMENTS = [
  { key: "recurringExpenses", label: "Gastos recurrentes", color: "#206B48" },
  { key: "variableExpenses", label: "Gastos variables estimados", color: "#7BCDC7" },
  { key: "savings", label: "Ahorro", color: "#F0B75B" },
] as const;

export function BudgetCard({ budget }: { budget: BudgetDTO }) {
  const [editOpen, setEditOpen] = useState(false);
  const [regenerating, startRegenerate] = useTransition();
  const { state, formAction } = useDialogAction(saveBudgetAction, () =>
    setEditOpen(false),
  );

  function handleRegenerate() {
    startRegenerate(async () => {
      const result = await regenerateBudgetAction();
      if (result.ok) toast.success(result.message);
    });
  }

  const monthLabel = new Date(budget.year, budget.month - 1).toLocaleDateString(
    "es-DO",
    { month: "long", year: "numeric" },
  );

  return (
    <Card>
      <CardHeader className="flex-row items-start justify-between space-y-0">
        <div>
          <CardTitle className="capitalize">Presupuesto · {monthLabel}</CardTitle>
          <CardDescription className="mt-1">
            {budget.isAutoGenerated
              ? "Propuesta generada con tus ingresos, gastos históricos, pagos recurrentes y metas."
              : "Presupuesto ajustado manualmente por ti."}
          </CardDescription>
        </div>
        <Badge variant={budget.isAutoGenerated ? "secondary" : "outline"}>
          {budget.isAutoGenerated ? (
            <>
              <Sparkles /> Sugerido
            </>
          ) : (
            "Personalizado"
          )}
        </Badge>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {/* Barra de distribución del ingreso */}
        {budget.income > 0 && (
          <div>
            <div className="flex h-4 w-full overflow-hidden rounded-full bg-muted">
              {SEGMENTS.map((s) => (
                <div
                  key={s.key}
                  className="h-full"
                  style={{
                    width: `${Math.min(100, (budget[s.key] / budget.income) * 100)}%`,
                    backgroundColor: s.color,
                  }}
                />
              ))}
              {budget.available > 0 && (
                <div
                  className="h-full bg-[#3E9B94]"
                  style={{ width: `${(budget.available / budget.income) * 100}%` }}
                />
              )}
            </div>
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">
              {SEGMENTS.map((s) => (
                <span key={s.key} className="inline-flex items-center gap-1.5">
                  <span
                    className="size-2.5 rounded-full"
                    style={{ backgroundColor: s.color }}
                  />
                  {s.label}
                </span>
              ))}
              <span className="inline-flex items-center gap-1.5">
                <span className="size-2.5 rounded-full bg-[#3E9B94]" />
                Disponible
              </span>
            </div>
          </div>
        )}

        {/* Desglose: ingresos − gastos − ahorro = disponible */}
        <div className="rounded-xl bg-muted/60 p-4">
          <dl className="space-y-2 text-sm">
            <div className="flex items-center justify-between">
              <dt className="text-muted-foreground">Ingresos</dt>
              <dd className="font-semibold tabular-nums">{formatMoney(budget.income)}</dd>
            </div>
            {SEGMENTS.map((s) => (
              <div key={s.key} className="flex items-center justify-between">
                <dt className="text-muted-foreground">− {s.label}</dt>
                <dd className="font-semibold tabular-nums">
                  {formatMoney(budget[s.key])}
                </dd>
              </div>
            ))}
            <Separator className="!my-3" />
            <div className="flex items-center justify-between text-base">
              <dt className="font-semibold">= Dinero disponible</dt>
              <dd
                className={cn(
                  "text-lg font-bold tabular-nums",
                  budget.available >= 0 ? "text-success" : "text-destructive",
                )}
              >
                {formatMoney(budget.available)}
              </dd>
            </div>
          </dl>
        </div>

        <div className="flex flex-col gap-2 sm:flex-row">
          <Button variant="outline" className="flex-1" onClick={() => setEditOpen(true)}>
            <Pencil /> Ajustar manualmente
          </Button>
          <Button
            variant="secondary"
            className="flex-1"
            onClick={handleRegenerate}
            disabled={regenerating}
          >
            {regenerating ? <Loader2 className="animate-spin" /> : <RefreshCw />}
            Recalcular sugerido
          </Button>
        </div>
      </CardContent>

      <Dialog open={editOpen} onOpenChange={setEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Ajustar presupuesto</DialogTitle>
            <DialogDescription>
              Modifica los montos mensuales; el dinero disponible se recalcula solo.
            </DialogDescription>
          </DialogHeader>
          <form action={formAction} className="flex flex-col gap-4">
            {!state.ok && <FormMessage state={state} />}
            {(
              [
                ["income", "Ingresos"],
                ["recurringExpenses", "Gastos recurrentes"],
                ["variableExpenses", "Gastos variables estimados"],
                ["savings", "Ahorro"],
              ] as const
            ).map(([key, label]) => (
              <FormRow key={key}>
                <Label htmlFor={`budget-${key}`}>{label} (RD$)</Label>
                <Input
                  id={`budget-${key}`}
                  name={key}
                  type="number"
                  inputMode="decimal"
                  min="0"
                  step="1"
                  defaultValue={Math.round(budget[key])}
                  required
                />
                <FieldError state={state} name={key} />
              </FormRow>
            ))}
            <SubmitButton className="w-full">Guardar presupuesto</SubmitButton>
          </form>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
